### ISSUE TITLE
Beta TODO list

### ISSUE THREAD

**Issue by IntelOrca** [biorand/re4r#1]
## Main issues
* [x] Random boss health
* [x] Drop randomizer
  * [x] Weapons
  * [x] Treasures
  * [x] Recipes, case drops, small keys, etc.
* [x] Static item randomizer
  * [x] Weapons
  * [x] Recipes, case drops, small keys, etc.
  * [x] Sliders
* [x] Tilted enemies (e.g. novis)
* [x] Guard DLC teasures from being weapons etc.
* [ ] Limit cabin to 1 mad chainsaw etc.
* [x] Some treasures don't work when randomized (e.g. pendant in farm)
* [x] Re-write UI
* [x] Add gunpowder, resource, rocket launcher stock per chapter
* [x] Disable mendez from all enemies with keys (inc. lantern)
* [x] Add slider for extra enemy %
* [x] Add ammo types to item/drop sliders
* [x] Add debug max enemy per stage sliders
* [x] Set various extra enemy spawn triggers
* [x] Update title screen title texture
* [x] Spawn ammo type only from chapter where gun is available
* [x] Ammo drops based on max stack
* [x] Extend timer on last segment
* [x] Progressive difficulty
* [x] Starting gun was a reward
* [x] Disable shop ammo, etc.
* [x] Improve treasure randomizer
* [x] Reduce red zealot pack size
* [x] Check snake boxes
* [x] Curve function sliders
* [x] Slider %
* [x] Krauser fight, don't randomize knife

## Minor issues
* [x] Assisted/Standard/Hardcode - Weapon upgrades not unlocked in Chapter 1
* [ ] Shop item textures are incorrect
* [x] Charm descriptions in shop are incorrect
* [x] Random base stats don't take effect.

## Nice to have
* [x] Shop - new items
* [x] Randomize weapon stats
* [x] Randomize weapon upgrade prices
* [x] Randomize weapon exclusive upgrades
* [x] Randomize base weapon stats
* [x] More typewriters
* [x] Lockers for Ashley to hide in
